version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run tests
          command: npm run test:ci
      - store_artifacts:
          path: ~/repo/test_results
